name: Test few GitHub Context
on:
  push:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu:latest
    steps:
      #run: echo "Job ID: ${{ github.run_id }}" 

    jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Job ID
        run: echo "Job ID: ${{ github.run_id }}_${{ github.job }}"
