name: Test few GitHub Context
on:
  push:
    branches: [ "main" ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Workflow Name
      run: echo "Workflow Name - ${{ github.workflow }}"
        
    - name: Print Workflow Run ID
      run: echo "Workflow Run ID - ${{ github.run_id }}"
